# 1.数据处理

In [3]:
import torch

In [33]:
torch.__version__, torch.version.cuda

('1.11.0', '11.3')

In [31]:
x = torch.arange(12)
x, x.shape, type(x)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 torch.Size([12]),
 torch.Tensor)

In [5]:
x.shape

torch.Size([12])

In [8]:
x1 = x.reshape(-1, 4)
x1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2, 3, 4,))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(3, 4)

tensor([[ 0.1987,  0.6433, -1.7542,  0.3348],
        [-1.7355,  0.0497, -1.0263,  0.6375],
        [ 0.6422,  0.0609, -0.9423, -0.4185]])

In [17]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).shape  # 嵌套列表，将列表也看作元素

torch.Size([3, 4])

In [25]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算
# 可通过，将输出的东西隔开，如果换行输出的话只会输出最下行的！！

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [24]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### dim=0即按行拼接，=1即按列拼接

In [33]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x, x.shape, y, torch.cat((x, y),dim=0), torch.cat((x, y),dim=1), torch.cat((x, y),dim=1).shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]),
 torch.Size([3, 8]))

In [35]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [37]:
x.sum()

tensor(66.)

## 1.2广播机制

In [4]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

### 广播机制，即a复制列为两列，b复制行为三行，使之都成为3×2的矩阵，从而对应元素再相加

In [5]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 1.3索引和切片

In [4]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X, X.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [7]:
X[-1], X[1:3, : ],X[1: 3], X[1, 3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(7.))

### 这里[1：3]表示这个张量其实本质还是有三个list，也就是三个元素，取第一和第二个,等同于[1:3, : ]

In [8]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
X[:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 9., 7.]])

### 这里：表示选中范围的所有列/行上的元素,[1:3, 1:]表示第一第二行上从第一列（含）上所有元素

In [23]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

###  这里'：：3'表示跳着2行/列选,选第0和第3，：：2表示跳一行选，第0和第2

In [24]:
X[1:3, 1:], X[::3, ::2]

(tensor([[12., 12., 12.],
         [ 9., 10., 11.]]),
 tensor([[12., 12.]]))

## 节省内存

### 若用Y=X+Y，则会产生一个新的内存用来存储原来的变量，但是改用Y[:],或者用Y += X则不会产生新的内存

In [28]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [29]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(X)
X[:] = X + Y
# X += Y
id(X) == before

True

## 转换对象

In [30]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)