In [1]:
import torch
import os
os.getcwd()

'F:\\doctor_learning\\DongShouXue\\d2l-zh\\class\\class2'

### 这里的".."表示当前目录的上一级，所以这个data文件夹建立再class2的上一级class文件夹中
### 这个exist_ok=True说如果该文件已经存在，也不报错

In [2]:
os.makedirs(os.path.join("..", 'data'), exist_ok=True)
data_file = os.path.join("..", 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

# 2.处理缺失值

### 使用iloc命令，将data分成input和output两类，分别进行切片处理
### 这个fillna命令是填充NaN值，使用当前列的均值进行填充，再NumRooms列中均值为3，则所有NaN替换为3

In [4]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


### 但是Aleey没有数字，从而算不出均值，故使用get_dummies命令，将Alley分为Pave和nan两列，各自类别分别对应1。该函数一般用来做独热编码one-hot
### dummy_na=True将缺失值也当作合法的特征值并为其创建指示特征

In [6]:
inputs = pd.get_dummies(inputs,  dummy_na=True)
print(inputs), inputs['numRooms']

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


KeyError: 'numRooms'

### 将对应的值转换成tensor，注意取值要用.values

In [28]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

# 作业：删除Nan最多的那一列数值

In [53]:
import pandas as pd
data = pd.read_csv(data_file)
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [54]:
inputs.isnull().sum() # 返回每一列缺失值的个数
a = inputs.isnull().sum()
inputs.isnull().sum().idxmax() # 得到缺失值最多的那一列的索引值（名称）
Max_Nan_Num=inputs.isnull().sum().idxmax()
inputs=inputs.drop(Max_Nan_Num,axis=1) # 删除缺失值最多的那一列
a, inputs


(NumRooms    0
 Alley       3
 dtype: int64,
    NumRooms
 0       3.0
 1       2.0
 2       4.0
 3       3.0)

In [57]:
x = torch.tensor(inputs.values)
x

tensor([[3.],
        [2.],
        [4.],
        [3.]], dtype=torch.float64)